In [66]:
import numpy as np
import pandas as pd

In [67]:
FILES = [
"/Users/joeyli/skillvsluck/data/european_soccer/data/Original_Matches.csv",
]
season_map = {
    f"I{i}": f"{2025 - i}/{2026 - i}" 
    for i in range(1, 25)
}
frames = []
for fp in FILES:
    df_i = pd.read_csv(fp, low_memory=False, on_bad_lines='skip')
    frames.append(df_i)

df_raw = pd.concat(frames, ignore_index=True)


columns =df_raw.columns

df_raw.sample(n=20)

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,...,MaxUnder25,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB
76128,F2,2012-04-06,NaN,Bastia,Guingamp,1545.13,1424.62,7.0,13.0,4.0,...,1.84,-1.0,1.79,2.06,NaN,NaN,NaN,NaN,NaN,NaN
180098,I2,2021-02-21,14:00:00,Reggina,Pordenone,1391.37,1451.81,7.0,9.0,3.0,...,1.64,-0.3,2.05,1.80,0.0216,0.8784,0.0419,0.0099,0.0245,0.0236
140209,AUT,2017-09-16,17:30:00,Admira,Sturm Graz,1454.98,1539.88,3.0,6.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179345,FIN,2021-02-05,16:30:00,KuPS,HJK,NaN,NaN,1.0,4.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10145,E3,2002-02-12,NaN,Lincoln,Mansfield,NaN,NaN,6.0,6.0,4.0,...,NaN,NaN,NaN,NaN,0.2520,0.0915,0.5643,0.0099,0.0430,0.0393
52833,SC0,2009-02-15,NaN,Celtic,Rangers,1660.63,1651.62,4.0,8.0,7.0,...,1.86,0.0,1.60,2.22,0.0401,0.5489,0.0308,0.0100,0.0212,0.3491
108843,RUS,2015-02-10,15:00:00,Ural,Krylya Sovetov,NaN,NaN,4.0,7.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163638,T1,2019-08-25,17:15:00,Trabzonspor,Yeni Malatyaspor,1543.65,NaN,7.0,11.0,3.0,...,2.44,-0.8,1.85,2.00,0.0546,0.2493,0.2330,0.0101,0.3645,0.0885
128773,NOR,2016-10-04,19:00:00,Viking,Odd,1336.72,NaN,3.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157059,I2,2019-01-25,NaN,Foggia,Crotone,1393.11,1409.96,4.0,7.0,1.0,...,1.91,-0.3,1.83,1.99,0.0190,0.0899,0.0173,0.0101,0.0405,0.8232
200023,SP2,2022-09-17,17:30:00,Granada,Mirandes,1631.14,1460.44,3.0,9.0,1.0,...,2.06,-1.0,1.83,2.02,0.8220,0.0391,0.0298,0.0355,0.0589,0.0147
34874,E3,2006-08-05,NaN,Grimsby,Boston,NaN,NaN,5.0,7.0,4.0,...,1.95,-0.5,1.99,1.80,0.1739,0.0765,0.2507,0.0113,0.3136,0.1739
157775,JAP,2019-02-11,06:00:00,Cerezo Osaka,Yamaga,NaN,NaN,6.0,7.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187421,BRA,2021-09-26,15:00:00,America MG,Flamengo RJ,NaN,NaN,5.0,6.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182003,I1,2021-04-07,17:45:00,Inter,Sassuolo,1892.38,1640.74,9.0,15.0,4.0,...,2.82,-1.5,2.01,1.92,0.1243,0.1394,0.0556,0.0614,0.4086,0.2108
126900,P1,2016-08-22,NaN,Sp Braga,Rio Ave,1595.39,1478.48,4.0,7.0,3.0,...,1.96,-1.0,2.02,1.79,NaN,NaN,NaN,NaN,NaN,NaN
157887,SP2,2019-02-16,NaN,Oviedo,Alcorcon,1562.31,1528.27,6.0,12.0,3.0,...,1.45,-0.3,1.79,2.01,0.0110,0.0338,0.0250,0.0184,0.8832,0.0286
107776,E2,2015-01-10,NaN,Peterboro,Colchester,NaN,NaN,1.0,4.0,4.0,...,2.04,-0.5,2.04,1.79,0.1001,0.0327,0.0523,0.0210,0.4470,0.3469
212592,F1,2023-09-30,20:00:00,Monaco,Marseille,1682.07,1700.86,4.0,8.0,2.0,...,2.55,-0.3,1.94,1.96,0.1161,0.2547,0.0100,0.1825,0.0446,0.3921
113010,ARG,2015-05-23,00:00:00,Crucero del Norte,Defensa y Justicia,NaN,NaN,1.0,4.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
columns

Index(['Division', 'MatchDate', 'MatchTime', 'HomeTeam', 'AwayTeam', 'HomeElo',
       'AwayElo', 'Form3Home', 'Form5Home', 'Form3Away', 'Form5Away', 'FTHome',
       'FTAway', 'FTResult', 'HTHome', 'HTAway', 'HTResult', 'HomeShots',
       'AwayShots', 'HomeTarget', 'AwayTarget', 'HomeFouls', 'AwayFouls',
       'HomeCorners', 'AwayCorners', 'HomeYellow', 'AwayYellow', 'HomeRed',
       'AwayRed', 'OddHome', 'OddDraw', 'OddAway', 'MaxHome', 'MaxDraw',
       'MaxAway', 'Over25', 'Under25', 'MaxOver25', 'MaxUnder25', 'HandiSize',
       'HandiHome', 'HandiAway', 'C_LTH', 'C_LTA', 'C_VHD', 'C_VAD', 'C_HTB',
       'C_PHB'],
      dtype='object')

In [69]:
need = ["Division","MatchDate", "HomeTeam", "AwayTeam", "HTHome", "HTAway", "HTResult", "OddHome","OddDraw","OddAway","MaxHome","MaxDraw","MaxAway","Over25","Under25","MaxOver25","MaxUnder25","HandiHome","HandiAway"]
have = [c for c in need if c in df_raw.columns]
df = df_raw[have].copy()


score_map_home = {"H": 3, "D": 1, "A": 0}
score_map_away = {"H": 0, "D": 1, "A": 3}

df.insert(loc=need.index("HTResult")+1, column="ScoreHome", value=df["HTResult"].map(score_map_home))
df.insert(loc=need.index("HTResult")+2, column="ScoreAway", value=df["HTResult"].map(score_map_away))


df.sample(n=10)


df_Bundesliga = df[df["Division"] == "D1"].copy()
df_La_Liga = df[df["Division"] == "SP1"].copy()

In [70]:
df_Bundesliga=df_Bundesliga.drop(columns = "Division")
df_La_Liga=df_La_Liga.drop(columns = "Division")

In [71]:
df_La_Liga

,MatchDate,HomeTeam,AwayTeam,HTHome,HTAway,HTResult,ScoreHome,ScoreAway,OddHome,OddDraw,OddAway,MaxHome,MaxDraw,MaxAway,Over25,Under25,MaxOver25,MaxUnder25,HandiHome,HandiAway
503,2000-09-09,Barcelona,Malaga,2.0,0.0,H,3.0,0.0,1.28,3.90,7.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,2000-09-09,La Coruna,Ath Bilbao,0.0,0.0,D,1.0,1.0,1.51,3.20,6.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505,2000-09-09,Real Madrid,Valencia,0.0,0.0,D,1.0,1.0,1.65,3.20,4.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,2000-09-09,Sociedad,Santander,0.0,0.0,D,1.0,1.0,1.85,3.15,3.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
507,2000-09-09,Zaragoza,Espanol,0.0,0.0,D,1.0,1.0,1.70,3.10,4.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230497,2025-05-24,Getafe,Celta,1.0,1.0,D,1.0,1.0,4.22,3.65,1.86,4.53,3.76,1.90,2.07,1.76,2.14,1.83,2.00,1.85
230498,2025-05-24,Vallecano,Mallorca,0.0,0.0,D,1.0,1.0,1.53,4.10,6.46,1.58,4.27,7.00,2.14,1.71,2.21,1.78,1.95,1.90
230499,2025-05-25,Girona,Ath Madrid,0.0,0.0,D,1.0,1.0,3.71,3.75,1.95,4.10,3.89,2.02,1.61,2.32,1.67,2.40,1.93,1.93
230500,2025-05-25,Villarreal,Sevilla,3.0,1.0,H,3.0,0.0,1.46,4.89,6.15,1.50,5.04,6.58,1.50,2.55,1.53,2.65,2.00,1.85
230535,2025-05-25,Ath Bilbao,Barcelona,0.0,2.0,A,0.0,3.0,3.22,3.75,2.11,3.35,3.89,2.18,1.52,2.49,1.55,2.55,2.00,1.85

In [72]:
df_Bundesliga["MatchDate"] = pd.to_datetime(df_Bundesliga["MatchDate"], errors="coerce", dayfirst=False)
df_La_Liga["MatchDate"] = pd.to_datetime(df_La_Liga["MatchDate"], errors="coerce", dayfirst=False)

def get_season(date):
    if pd.isna(date):
        return None
    year = date.year
    if date.month >= 8:  # August → season starts this year
        return f"{year}" #/{year+1}
    else:  # Jan–July → season is last year
        return f"{year-1}" #/{year}


df_Bundesliga["season"] = df_Bundesliga["MatchDate"].apply(get_season)
df_La_Liga["season"] = df_La_Liga["MatchDate"].apply(get_season)

# Move season to the front of the df
col = "season"

# Get all columns, remove the one you want to move
cols = [col] + [c for c in df_Bundesliga.columns if c != col]

# Reorder the DataFrame
df_Bundesliga = df_Bundesliga[cols]

df_La_Liga = df_La_Liga[cols]

In [73]:
final_Bundesliga_df = df_Bundesliga.sort_values(
    ["season", "MatchDate"], 
    ascending=[False, False],   # season desc, date desc
    ignore_index=True
)

final_La_Liga_df = df_La_Liga.sort_values(
    ["season", "MatchDate"], 
    ascending=[False, False],   # season desc, date desc
    ignore_index=True
)

In [74]:
final_Bundesliga_df.to_csv("Bundesliga_Final_Data.csv", index=False)
final_La_Liga_df.to_csv("La_Liga_Final_Data.csv", index=False)